### ISSUE TITLE
Type error: Argument 1 passed to Kreait\Firebase\Factory::withVerifierCache() must be an instance of Psr\SimpleCache\CacheInterface, instance of Illuminate\Cache\Repository given

### ISSUE THREAD

**Issue by Lordofcodes** [kreait/laravel-firebase#1]
I am using laravel 5.2 and the error is coming from below file.
vendor\kreait\laravel-firebase\src\ServiceProvider.php on line 55.

 ```
if ($cacheStore = $config['cache_store'] ?? null) {
                $factory = $factory->withVerifierCache(
                    $app->make('cache')->store($cacheStore)// from here
                );
            }
```

**Comment by jeromegamez** [comment]
This package needs Laravel 5.8 to work properly with cache (see https://github.com/laravel/framework/pull/20194). I will add this information to the README.

What you could try is disabling the cache, by first publishing the config for the package with 

```bash
php artisan vendor:publish --provider="Kreait\Laravel\Firebase\ServiceProvider" --tag=config
```

and then setting the `cache_store` setting to `null`.

**Comment by Lordofcodes** [comment]
@jeromegamez  Thanks fixed.  I just set `FIREBASE_CACHE_STORE=null` in `.env` file.

**Comment by jeromegamez** [comment]
@Lordofcodes Please keep in mind that you will now have to stay on 1.0.0 of the release forever 😅 (or until you upgrade your Laravel application to 5.8)

**Comment by Lordofcodes** [comment]
@jeromegamez  Not a problem.  Thank you so much.👏😊
