### ISSUE TITLE
trying to login a firestore user using php 

### ISSUE THREAD

**Issue by mindful-devs** [kreait/laravel-firebase#10]
I am new to cloud firestore. I am looking for a similar way in php like in javascript to login user and get access to database. I am reffereing to the following code but need that code in php.
firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
  // Handle Errors here.
  var errorCode = error.code;
  var errorMessage = error.message;
  // ...
});

also I have the following rules setup on the firestore database.
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}

Any help will higly be appriciated!

**Comment by jeromegamez** [comment]
That's currently not possible with the SDK - it's on my todo list but will require some serious rewrites, so there's, unfortunately, no ETA.

**Comment by jeromegamez** [comment]
Please follow the releases of https://github.com/kreait/firebase-php to get notified when this feature might be implemented.
