### ISSUE TITLE
Invalid Token when deploy on Vercel

### ISSUE THREAD

**Issue by denusklo** [kreait/laravel-firebase#100]
The issue occur when I deploy my web app on Vercel.

The error message:
```
The token is invalid: file_put_contents(/var/task/user/storage/framework/cache/data/24/fc/24fc69d48eaa682f929a7045e8f4700237c0083e): failed to open stream: No such file or directory
```
Everything is fine on localhost but when I deploy. it sads.

**Comment by jeromegamez** [comment]
This seems to be an issue with running Laravel on Vercel, not an issue directly related to this package - I'm afraid I can't provide free support for issues not directly related to this library, I hope you can understand 🙏
