### ISSUE TITLE
Using multiple database in firebase is not supported

### ISSUE THREAD

**Issue by dyros26** [kreait/laravel-firebase#101]
If this is supported can you provide a documentation on how to use other database?

**Comment by jeromegamez** [comment]
You can configure [multiple projects](https://github.com/kreait/laravel-firebase#multiple-projects) with the same credentials but different database URLs, I hope this helps 🤞

**Comment by Zein0** [comment]
@jeromegamez late question I've tried this but its still getting the default database
I'm using https://test-export.firebaseio.com/ as my second db is called test-export is this correct?
and what is the link of my default one then?
