### ISSUE TITLE
Unable to connect to the API: cURL error 6

### ISSUE THREAD

**Issue by essamtariq123** [kreait/laravel-firebase#105]
I am using this package and when I write 

$newPost = app('firebase.database')->getReference('users')
     ->push([
    'name' => 'sample name' ,
    'email' => 'sample email',
    'accountType' => 'sample'
    ]);

it gives me an error 

Kreait\Firebase\Exception\Database\ApiConnectionFailed
Unable to connect to the API: cURL error 6: Could not resolve host: users.json (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
![Screenshot 2021-09-01 at 2 47 27 PM](https://user-images.githubusercontent.com/45160841/131682959-13bbfe8a-227e-471c-9841-bc8efaf5bf55.png)

can you please help me resolve the issue. thanks

**Comment by jeromegamez** [comment]
Please have a look at https://firebase-php.readthedocs.io/en/5.x/troubleshooting.html#curl-error-xx

cURL error 6 (`CURLE_COULDNT_RESOLVE_HOST (6)` https://curl.se/libcurl/c/libcurl-errors.html) hints at a networking issue 🤔
