### ISSUE TITLE
Firebae notification topic limit.

### ISSUE THREAD

**Issue by Nits7029** [kreait/laravel-firebase#107]
I'm using firebase topic messaging for bulk notifications.
What I want to know is what is app instanc in firebase's documentation.
It says one app instance can subscribe no more than 2000 topics,if so how can I use topics for millions of users. 
and if there is a limit then how others are managing.

https://firebase.google.com/docs/cloud-messaging/android/topic-messaging

**Comment by jeromegamez** [comment]
This is a 3rd party library and the issue tracker here is intended for bugs and issues concerning the library - for questions about Firebase (the service) you could ask Firebase directly or on StackOverflow 🙏

That being said: the 2000 topic limit relates to App Instances (=devices/browsers on which your application is installed), not the  number of topics in total.

If you have millions of App instances, each of the instances can be subscribed to up to 2000 topics.

I hope this helps 🤞

**Comment by Nits7029** [comment]
That makes sense, 
Thanks you @jeromegamez.
