### ISSUE TITLE
The registration token is not a valid FCM registration token

### ISSUE THREAD

**Issue by robertnicjoo** [kreait/laravel-firebase#108]
I've downloaded my adminsdk from firebase and add it to my env file like `FIREBASE_CREDENTIALS="config/xxxx-xxxx-firebase-adminsdk-xxxx-xxxx.json"` but when I'm trying to send notification it returns this error

```sh
[2021-09-24 11:48:42] local.ERROR: The registration token is not a valid FCM registration token {"userId":1,"exception":"[object] (Kreait\\Firebase\\Exception\\Messaging\\InvalidMessage(code: 0): The registration token is not a valid FCM registration token at /home/xxxxxxx/domains/xxxxxxx/vendor/kreait/firebase-php/src/Firebase/Exception/Messaging/InvalidMessage.php:22)
```

here is my code:

```php
$uu = User::where('id', $request->input('senderId'))->first();
$deviceToken = $uu->app_token;
if(!empty($deviceToken)) {
    $factory = Firebase::auth();
    $notification = Notification::fromArray([
        'token' => $deviceToken, // token of receiver user device
        'title' => $uu->name,
        'body' => $message->note,
        'image' => null,
    ]);

    $config = ApnsConfig::fromArray([
        'headers' => [
            'apns-priority' => '10',
        ],
        'payload' => [
            'aps' => [
                'alert' => [
                    'title' => $uu->name,
                    'body' => $message->note,
                ],
                'badge' => 42,
                'sound' => 'default',
            ],
        ],
    ]);

    $messaging =  app('firebase.messaging');
    $dataToSend = [
        'to_userId' => $request->input('senderId') == $mess->chat->asReceiver->id ? $mess->chat->asSender->id : $mess->chat->asReceiver->id,
        'from_userId' => $request->input('senderId'),
        'chat_id' => $chat->id,
        'type' => 'privatechat',
        'click_action' => 'FLUTTER_NOTIFICATION_CLICK',
    ];
    $message = CloudMessage::withTarget('token', 'rtc')
        ->withNotification($notification)
        ->withHighestPossiblePriority()
        ->withDefaultSounds()
        ->withApnsConfig($config)
        ->withData($dataToSend);
    $m = $messaging->send($message);
}
```

**Comment by jeromegamez** [comment]
`CloudMessage::withTarget('token', 'rtc')`

Make sure that you use a valid registration token where you currently have `rtc`

**Comment by robertnicjoo** [comment]
> `CloudMessage::withTarget('token', 'rtc')`
> 
> Make sure that you use a valid registration token where you currently have `rtc`

Thank you, can I have both token and topic at the same time?

**Comment by jeromegamez** [comment]
For anyone else stumbling upon this: It's not possible to send a message to a token and a topic simultaneously, so you'll need two messages to achieve this, for example with:

```php
$messaging = $factory->createMessaging();

$message = CloudMessage::new()
    ->withNotification(['title' => 'Title', 'body' => 'Body']);

$messaging->send($message->withChangedTarget('token', '...'));
$messaging->send($message->withChangedTarget('topic', '...'));
```

**Comment by VigSqd** [comment]
@jeromegamez If so how can we validate the fcm tokens before sending a notification? I am using this code and it gives me error no valid tokens provided. As per the document it should return an array of invalid, unknown and valid tokens. but its not. In below code i added some wrong tokens in the db to check if it filters out the valid one, but it only returns exception that no valid tokens.

`$staticToken = "fTEytEaDYU21lvf9n2cU5A:APA91bF6yEukPKO351sRdOfTRP6IYi7wR3IVc_QTAawwmeJgA5B2MWJwRCk4H8d_OaXZolfZs0LSjE7D-uofw5Jd26mKobWcko86l7zUK89y3yl8nelkiEo8351Hv8vYwbKa-sWYIQNT";
    $fcmTokens = Device::where('user_id', $id)->pluck('fcmtoken');
    $fcmTokens->push($staticToken);
        try {
            $result = $this->notification->validateRegistrationTokens($fcmTokens);
        } catch (\Throwable $th) {
            //throw $th;
            echo $th;
        } `

**Comment by jeromegamez** [comment]
I don't know what code you provided here, but it's certainly not from the SDK 😅. You should ask the creator of the code/library, perhaps they're using an old version of the SDK and/or abstracting away things.
