### ISSUE TITLE
Config to disable Cloud Messaging

### ISSUE THREAD

**Issue by fabiomlferreira** [kreait/laravel-firebase#112]
I'm having a problem, I have a project that is already in production, and I'm working in the development project but I don't have a easy way to disable the Cloud Messaging to prevent to spam real clients.

The only solution that I found is to create a second firebase account and use that credentials but I think we should have a config for .env to disable Firebase, for example FIREBASE_ENABLED=false.

**Comment by devglrd** [comment]
Feel free to make a PR

**Comment by jeromegamez** [comment]
I think a PR won't help 😅. Having a separate Firebase project is currently the recommended (only) way to do it with the PHP SDK, and was the only way to do it before Google released the emulator suite. Support for the emulators will come eventually, but I can't tell you when.

Perhaps I will be able to add a NOOP implementation before that, but I'm currently on vacation and don't know when I'll have the resources for it, so I don't have an ETA for that either.

**Comment by ankurk91** [comment]
One can use the Laravel events

```php
 \Illuminate\Notifications\Events\NotificationSending::class => [
            \App\Listeners\Notification\PreventFCMWhenDisabled::class,
        ],
```

**Comment by jeromegamez** [comment]
I'm closing this issue because using a separate project remains the only way to do it with the SDK. It now has support for the Emulator Suite, but there's no emulator for FCM (yet).

I haven't tested if/how @ankurk91's suggestion works, but perhaps the can elaborate so that you can implement this as well.
