### ISSUE TITLE
Update for PHP 8.1

### ISSUE THREAD

**Issue by repat** [kreait/laravel-firebase#115]
Hi,

v.3.0.0 allows for PHP 8.1 (`^8.0`) and my preliminary testing (FCM notification for my phone) confirms it's working. However, `^3.1` goes back to PHP `~8.0`, not sure why? Can you look into officially supporting PHP 8.1?

I know PHP 8.1 has just been released end of last week but I just wanted to leave an issue for this :-)

Thanks!

**Comment by jeromegamez** [comment]
PHP 8.1 wasn't released at the time, and I'm often switching between not wanting to block people testing with yet-unreleased PHP versions and only supporting what I can actually confidently support 😅.

PHP 8.1 support was re-added with https://github.com/kreait/laravel-firebase/pull/110/, I just forgot to release it, which is now done with [3.3.0](https://github.com/kreait/laravel-firebase/releases/tag/3.3.0) - thank you for the nudge!
