### ISSUE TITLE
The path of a URI with an authority must start with a slash "/" or be empty

### ISSUE THREAD

**Issue by Frtrillo** [kreait/laravel-firebase#116]
When I do: 

 $reference->remove();

I get the following error:
The path of a URI with an authority must start with a slash "/" or be empty

This is on Laravel 8. Maybe its related to this issue: https://github.com/kreait/firebase-php/issues/663 and you could fix it? T

**Comment by jeromegamez** [comment]
This looks indeed as if it was the same issue as in https://github.com/kreait/firebase-php/issues/663 - this can be solved by installing the latest release of the underlying SDK (at least 5.24). Which version is your project using? You can check with `composer outdated` and in case you have an older dependency installed, update it with `composer update -W` - either for your whole project or just the Laravel package.
