### ISSUE TITLE
Laravel-Firebase Data insertion error

### ISSUE THREAD

**Issue by alikashi543211** [kreait/laravel-firebase#119]
Target [Kreait\Firebase\Contract\Database] is not instantiable while building [App\Http\Controllers\Firebase\ContactController]. 

My firebase connectivity creating an error when i add constructor.

Help to me to resolve it . Thank You !!

**Comment by jeromegamez** [comment]
Could you please provide more information? What version of Laravel and the package are you using? How can I reproduce your error?
