### ISSUE TITLE
Web push with link option doesn't work

### ISSUE THREAD

**Issue by Stajor** [kreait/laravel-firebase#123]
Code from the [documentations](https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#webpush)
```php
        $config = WebPushConfig::fromArray([
            'notification' => [
                'title' => '$GOOG up 1.43% on the day',
                'body' => '$GOOG gained 11.80 points to close at 835.67, up 1.43% on the day.',
                'icon' => 'https://my-server/icon.png',
            ],
            'fcm_options' => [
                'link' => 'https://my-server/some-page',
            ],
        ]);
```

Throws exception
```
In InvalidMessage.php line 22:
Invalid JSON payload received. Unknown name "link" at 'message.fcm_options': Cannot find field.  
```

**Comment by jeromegamez** [comment]
Please provide a reproducible code snippet and/or the full message that you've sent to the Firebase Servers. Also, please share which version of the SDK you're using.

According to https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#WebpushConfig the code looks correct so far.
