### ISSUE TITLE
Please, getting lots of errors while instaling

### ISSUE THREAD

**Issue by JhonatanGarcia92** [kreait/laravel-firebase#126]
root@c6593b99f1b9:/var/www/html# composer require kreait/laravel-firebase
Using version ^4.1 for kreait/laravel-firebase
./composer.json has been updated
Running composer update kreait/laravel-firebase
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - kreait/firebase-php[6.0.0, ..., 6.x-dev] require lcobucci/jwt ^4.1 -> found lcobucci/jwt[4.1.0, ..., 4.2.x-dev] but the package is fixed to 3.2.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/laravel-firebase 4.1.0 requires kreait/firebase-php ^6.0 -> satisfiable by kreait/firebase-php[6.0.0, ..., 6.x-dev].
    - Root composer.json requires kreait/laravel-firebase ^4.1 -> satisfiable by kreait/laravel-firebase[4.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require kreait/laravel-firebase:*" to figure out if any version is installable, or "composer require kreait/laravel-firebase:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
    
    
 My composer.json
    
  ```  {
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "ext-curl": "*",
        "ext-dom": "*",
        "ext-json": "*",
        "arcanedev/log-viewer": "^8.2",
        "dingo/api": "^3.0.7",
        "doctrine/dbal": "3.1.1",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "intervention/image": "^2.7",
        "laravel/framework": "^8.6.10",
        "laravel/helpers": "^1.0@dev",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "^1.0",
        "opencage/geocode": "^3.1",
        "predis/predis": "^2.0.x-dev",
        "spatie/laravel-permission": "^5.1",
        "spatie/laravel-url-signer": "^2.6.1",
        "tymon/jwt-auth": "^1.0.2",
        "webpatser/laravel-uuid": "^4.0",
        "kreait/laravel-firebase": "^4.1.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.10.0",
        "brianium/paratest": "^6.3",
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "filp/whoops": "~2.14.0",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "pestphp/pest": "^1.15",
        "phpunit/phpunit": "^9.3.3",
        "symfony/thanks": "^1.2.10",
        "squizlabs/php_codesniffer": "^3.6"
    },
    "autoload": {
        "files": [
            "app/Helpers/Helper.php"
        ],
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "tests": [
            "./vendor/phpunit/phpunit/phpunit tests"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "symfony/thanks": true,
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
  ```

**Comment by jeromegamez** [comment]
This is due to the tymon/jwt-auth package preventing the installation of a required dependency. You can read more about it at https://github.com/kreait/firebase-php/discussions/581
