### ISSUE TITLE
[Auth] Unresolvable dependency

### ISSUE THREAD

**Issue by azzazkhan** [kreait/laravel-firebase#130]
# Error
`Unresolvable dependency resolving [Parameter #0 [ <required> string $projectId ]] in class Kreait\Firebase\Auth\ApiClient`

# How to reproduce
Code snippet from `web.php` file.
```php
use Illuminate\Support\Facades\Route;
use Kreait\Firebase\Auth as FirebaseAuth;

Route::get('/', function (FirebaseAuth $auth) { // Binding resolution error
    // return view('welcome');
});
```

# Expected behavior
Should resolve dependency without throwing any errors

# Environment
OS: Ubuntu 20.04
PHP: 8.1.4
Composer: 2.3.3
laravel/framework: ^9.2
kreait/laravel-firebase: ^4.1

**Comment by jeromegamez** [comment]
Please see this issue that describes the same problem

https://github.com/kreait/firebase-php/issues/696#issuecomment-1086661275

Alternatively, have a look at the readme of the package, you'll find the correct usage there.

(Please excuse the short answer without more links, I'm currently on vacation and have only my phone with me)
