### ISSUE TITLE
composer require kreait/laravel-firebase - can't install package

### ISSUE THREAD

**Issue by just-Luka** [kreait/laravel-firebase#150]
I've been trying to install package through composer, it runs okay but soon getting back error says

> Failed to download stella-maris/clock from dist: The "https://gitlab.com/api/v4/projects/stella-maris%2Fclock/repository/archive.zip?sha=447879c53ca0b2a762cdbfba5e76ccf4deca9158" file could not be downloaded (HTTP/2 503 )
    Now trying to download from source
  - Syncing stella-maris/clock (0.1.5) into cache
Cloning failed, enter your GitLab credentials to access private repos

**Comment by jeromegamez** [comment]
GitLab is currently going through scheduled maintenance and should be available in the next hour or two

https://status.gitlab.com/

**Comment by just-Luka** [comment]
Oh alright. Thanks such a quick response :)

**Comment by jeromegamez** [comment]
You're welcome! 🙌
