### ISSUE TITLE
Version support Laravel 5.8 and PHP 7.1.3?

### ISSUE THREAD

**Issue by quocthi2005** [kreait/laravel-firebase#153]
I installed this package with version 1.5.0 and get an error when call app('firebase.messaging')

> syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)

**Comment by jeromegamez** [comment]
I'm sorry, but I can't provide support for outdated versions of this package, Laravel or PHP, I hope you can understand!
