### ISSUE TITLE
Firebase Admin SDK AppCheck

### ISSUE THREAD

**Issue by bardolf69** [kreait/laravel-firebase#158]
### Describe the feature you would like to see

I was wondering if it is possible to add support for the AppCheck token verification.  [(https://firebase.google.com/docs/app-check/custom-resource-backend)](https://firebase.google.com/docs/app-check/custom-resource-backend)

**Comment by jeromegamez** [comment]
He there 👋🏻,

yes, AppCheck token verification is coming soon in the upcoming 7.0 release. There's an open issue at https://github.com/kreait/firebase-php/issues/693 and a PR at https://github.com/kreait/firebase-php/pull/747 - if you follow one of them; you should get notified when it's done, it shouldn't take too long anymore. 🤞🏻
