### ISSUE TITLE
Access Credentials 

### ISSUE THREAD

**Issue by Nao-30** [kreait/laravel-firebase#178]
sorry but could someone provide a more detailed setup for the .env file?

i could not know which credentials are needed

is it the API key or sender id or access tokens or what exactly?

**Comment by jeromegamez** [comment]
The "Configuration" section of the README tells you about the needed credentials; you'll need a Google/Firebase Service Account - https://firebase-php.readthedocs.io/en/stable/setup.html explains how to get one.

**Comment by Nao-30** [comment]
I see now, I didn't realize that.
I was trying to find the "other way" mentioned, like setting some keys in the .env, then i knew i needed to keep it json anw
but now that i see the credentials json file i understand why, warm regards.
