### ISSUE TITLE
Unable to Connect CURL Error:28

### ISSUE THREAD

**Issue by VigneshSundhar4398** [kreait/laravel-firebase#183]
### Describe the bug

While i use firebase service thorugh this package i got a issue like this **Unable to connect to the API:cURL error 28:Failed to connect to ruzmozd-db2fc-default-rtdb.firebaseio.com port 443:Connection Timed out**
![Screenshot_20230525-194022](https://github.com/kreait/laravel-firebase/assets/135027868/54df7fd0-929d-49d4-8c33-980d9fb58acc)

### Installed packages

```json
"kreait/firebase-php": "6.9.0",
```

### PHP version and extensions

```shell
"php": "^8.1",
```

### Steps to reproduce the issue.

```shell
# Insert the commands issued in the terminal if they are needed
# to reproduce the issue. Otherwise, delete this code block.
```

```php
// Insert the PHP code to reproduce the issue. Please ensure that it is code that
// can be copy pasted to reproduce it.
```

### Error message/Stack trace

```shell
.
```

### Additional information

.

**Comment by jeromegamez** [comment]
Unfortunately, as the error message says, this is a connection/network problem between where your application is running and the Firebase servers, either on your side or on the side of Firebase.

Unfortunately, this is nothing that can be fixed from within the SDK.
