### ISSUE TITLE
No publishable resources for tag []. Publishing complete.

### ISSUE THREAD

**Issue by mahmoudkhalifa84** [kreait/laravel-firebase#193]
### Describe the bug

No publishable resources for tag [].
Publishing complete.

### Installed packages

```json
No publishable resources for tag [].
Publishing complete.
```

### PHP version and extensions

```shell
8.13
```

### Steps to reproduce the issue.

```shell
# Insert the commands issued in the terminal if they are needed
# to reproduce the issue. Otherwise, delete this code block.
```

```php
// Insert the PHP code to reproduce the issue. Please ensure that it is code that
// can be copy pasted to reproduce it.
```

### Error message/Stack trace

```shell
No publishable resources for tag [].
Publishing complete.
```

**Comment by jeromegamez** [comment]
You can publish the configuration with

```php
php artisan vendor:publish --provider="Kreait\Laravel\Firebase\ServiceProvider" --tag=config
``` 

It makes sense that there are no resources for non-provided (`[]`) tags

**Comment by mahmoudkhalifa84** [comment]
> ```
> ```
> php artisan vendor:publish --provider="Kreait\Laravel\Firebase\ServiceProvider" --tag=config
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

when i run this command i got this error "No publishable resources for tag [config]. Publishing complete."

**Comment by jeromegamez** [comment]
In that case I'll need more information - which Laravel version are you using and which version of the package 🙏🏻

**Comment by mahmoudkhalifa84** [comment]
> In that case I'll need more information - which Laravel version are you using and which version of the package 🙏🏻

Laravel Framework 8.83.27  after i install firebase with composer require kreait/laravel-firebase,
 i want to publish this package with 

php artisan vendor:publish --provider="Kreait\Laravel\Firebase\ServiceProvider" --tag=config

i got this error "No publishable resources for tag [config]. Publishing complete."

any advice please ?

**Comment by jeromegamez** [comment]
You didn't tell me the installed version of this package, but from your Laravel version I can tell that it's a 3.x version. I provide support only for the latest major version.

Also, I would like to recommend you to read https://berthub.eu/articles/posts/anonymous-help/ and https://github.com/kreait/firebase-php/issues/817#issuecomment-1656251729.
