### ISSUE TITLE
Support PHP8.3

### ISSUE THREAD

**Issue by augusl** [kreait/laravel-firebase#207]
### Describe the feature you would like to see

  Problem 1
    - Root composer.json requires kreait/laravel-firebase ^5.2 -> satisfiable by kreait/laravel-firebase[5.2.0, 5.3.0, 5.4.0].
    - kreait/laravel-firebase[5.2.0, ..., 5.4.0] require php ~8.1.0 || ~8.2.0 -> your php version (8.3.0) does not satisfy that requirement.

**Comment by jeromegamez** [comment]
🚀  PHP 8.3 is supported since https://github.com/kreait/laravel-firebase/releases/tag/5.5.0
