### ISSUE TITLE
Make Support For Laravel 11

### ISSUE THREAD

**Issue by MohammedElattar** [kreait/laravel-firebase#215]
### Describe the feature you would like to see

![Screenshot_20240313_105748](https://github.com/kreait/laravel-firebase/assets/93054654/63de9e02-cc52-446a-aad7-69cc8de06a32)

**Comment by AmmadGetlicensed** [comment]
<img width="1026" alt="image" src="https://github.com/kreait/laravel-firebase/assets/119588623/5877dd8b-d44e-469c-9b42-ee2d507046c5">
Same with me. please make support for Laravel 11.

**Comment by jeromegamez** [comment]
Please follow #214
