### ISSUE TITLE
Unable to create a FirestoreClient

### ISSUE THREAD

**Issue by diadal** [kreait/laravel-firebase#22]
`Unable to create a FirestoreClient: Class 'Google\Cloud\Firestore\FirestoreClient' not found`

```
$database = app('firebase.firestore')->database();

        $var_list = $database->collection('tokens')->document('tokens')->snapshot();

        return [$var_list];
```

**Comment by jeromegamez** [comment]
```sh 
composer require google/cloud-firestore
```

The Firestore library is not included out of the box because it require the `grpc` PHP extension which is not enabled by default and would break the SDK for most users.

See https://firebase-php.readthedocs.io/en/stable/cloud-firestore.html
