### ISSUE TITLE
Log Channel Not Working

### ISSUE THREAD

**Issue by circuitmamu** [kreait/laravel-firebase#223]
### Describe the bug

I have my own custom channel named `activity`
```

LOG_CHANNEL=daily
FIREBASE_HTTP_LOG_CHANNEL=activity
FIREBASE_HTTP_DEBUG_LOG_CHANNEL=activity
```

my .env values is like above

$member->notify(new \App\Notifications\TransactionSuccess($data));
inside constructer of notification 
\Illuminate\Support\Facades\Log::setDefaultDriver('activity');
\Illuminate\Support\Facades\Log::info('This is test msg only need in activity');
        
When I called test log is in activity file and notitification is goes to quque which is clear every minute and at that time my log of firebase is not coming to activity file

Am I missing something?        

### Installed packages

```json
classified
```

### PHP version and extensions

```shell
PHP 8.2.0 with all necessary extension
```

### Steps to reproduce the issue.

you can do with any notification that uses via \NotificationChannels\Fcm\FcmChannel\FcmChannel:class

### Error message/Stack trace

```shell
No errors
```

### Additional information

when notification run through job logs generating to other files

**Comment by jeromegamez** [comment]
Classified, huh.

I don't maintain the  FCM Notification Channel, you might want to raise the issue here:

https://github.com/laravel-notification-channels/fcm
