### ISSUE TITLE
FCM APIs depreciated as of July 22 2024

### ISSUE THREAD

**Issue by andrewP-ME** [kreait/laravel-firebase#230]
### Describe the feature you would like to see

The FCM APIs used by the package have now been depreciated - the API endpoints need to be updated - for more details see here:

https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by jeromegamez** [comment]
The SDK has been using the new API endpoints since they've been introduced. If you're running into issues, please update your dependencies.
