### ISSUE TITLE
Not Send Puchnotification

### ISSUE THREAD

**Issue by ketanmprajapati** [kreait/laravel-firebase#26]
Hello Kreait
i have setup all the thing but i got error like

**Kreait\\Firebase\\ServiceAccount\\Discovery\\FromEnvironmentVariable: The environment variable \"FIREBASE_CREDENTIALS\" is not set.\nKreait\\Firebase\\ServiceAccount\\Discovery\\FromEnvironmentVariable: The environment variable \"GOOGLE_APPLICATION_CREDENTIALS\" is not set.\nKreait\\Firebase\\ServiceAccount\\Discovery\\FromGoogleWellKnownFile: The well known file is not readable or invalid\ncURL error 6: Could not resolve host: metadata.google.internal; Unknown error (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)**

can you please give me some solution.

**Comment by jeromegamez** [comment]
Please read the README of the library and the contents of the error: You need to define the variable `FIREBASE_CREDENTIALS` in your .env file and set it to the path to your credentials file.

**Comment by ketanmprajapati** [comment]
Dear jeromegamez
I have already defined the variable on .env file and give to the path for my credentials file but still, I got the same error
![tempsnip](https://user-images.githubusercontent.com/33022239/76059448-e0433e80-5fa4-11ea-84eb-2c1e92d710a8.png)

**Comment by jeromegamez** [comment]
Based on the only information you gave me, this is the only solution I can give you. 

Without real code, file names and file paths I can only guess what the problem might be. What is the code you‘ve written that caused the error? Have you changed Firebase related settings?
