### ISSUE TITLE
Validating FCM token with laravel POST request

### ISSUE THREAD

**Issue by neri4488** [kreait/laravel-firebase#27]
I successfully created the service account and am using automatic detection of the .json file download from firebase.
I can validate the tokens generated and get the expected results when I invoke the method through php artisan command, but when I invoke the method with the POST request, I get the exception message bellow, kindly help me because I used the Artisan commands just to test my integration.

`Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "FIREBASE_CREDENTIALS" points to "firebase/noregrets-app-firebase-adminsdk-gyz53-b5fe293de1.json", but has errors: Invalid service account specification
Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "GOOGLE_APPLICATION_CREDENTIALS" is not set.
Kreait\Firebase\ServiceAccount\Discovery\FromGoogleWellKnownFile: The well known file is not readable or invalid
cURL error 6: Could not resolve host: metadata.google.internal (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (Kreait\\Firebase\\Exception\\ServiceAccountDiscoveryFailed(code: 0): Kreait\\Firebase\\ServiceAccount\\Discovery\\FromEnvironmentVariable: The environment variable \"FIREBASE_CREDENTIALS\" points to \"firebase/noregrets-app-firebase-adminsdk-gyz53-b5fe293de1.json\", but has errors: Invalid service account specification
Kreait\\Firebase\\ServiceAccount\\Discovery\\FromEnvironmentVariable: The environment variable \"GOOGLE_APPLICATION_CREDENTIALS\" is not set.
Kreait\\Firebase\\ServiceAccount\\Discovery\\FromGoogleWellKnownFile: The well known file is not readable or invalid`

Expected results when converted to json:

`{"application":"webpush","authorizedEntity":"555594871987","platform":"BROWSER"}`

This is the method that validates the token:

`public static function validateToken(string $token)
    {
        $messaging = (new Factory())->createMessaging();

        try {
            $appInstance = $messaging->getAppInstance($token);
            return $appInstance->rawData();
        } catch (FirebaseException $e) {
            Log::alert($e->getMessage());
            return false;
        }
    }`

This is how I invoke the method with artisan command in routes/console.php file:
`Artisan::command('validate-token', function () {

    $token = $this->ask('Enter device token');

    $res = FirebaseApp::validateToken($token);

    $this->comment(json_encode($res));

})->describe('Validate fcm token test');`

This is how I invoke the method with a post request in my controller file:

`public function fcmToken(Request $request)
    {
        $token = $request->get("fcm_token");
        //Validate token
        $raw_data = FirebaseApp::validateToken($token);

        if (!$raw_data) {
            return response()->json("Invalid registration token");
        }
}`

**Comment by neri4488** [comment]
I also tried this but no expected results with POST request
`$env:GOOGLE_APPLICATION_CREDENTIALS="C:\Users\username\Downloads\service-account-file.json"`

**Comment by jeromegamez** [comment]
I‘m not sure I understand - the same code works in the console, but not in the browser? Is it possible that your request goes to a different project/environment, where the .env file is not evaluated? Perhaps caches must be cleared (just thinking out loud)

A note: Please check the README... don‘t use the `Factory` inside your code - the package already does the configuration for you; if you use the `Factory` directly, you don‘t use that configuration (and would not need the Laravel package)

**Comment by neri4488** [comment]
Thanks, I went again to the read me. Before I could not see [this here](https://github.com/kreait/laravel-firebase#license), I can surely say, using `Factory` caused all this behavior.

**Comment by aminechraibi** [comment]
Use this instead worked for me
use Kreait\Firebase\Messaging;

`public function isValidFireBaseToken($token)
{
    try {
        // $messaging = (new Factory())->createMessaging();
        $messaging = app()->make(Messaging::class);
        $appInstance = $messaging->getAppInstance($token);
        return $appInstance->rawData();
    } catch (\Throwable $e) {
        echo $e->getMessage();
        Log::error($e->getMessage());
        return false;
    }
}`
