### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by benjnp** [kreait/laravel-firebase#32]
Hi,

Anybody here having the issue:
**Unable to locate publishable resources.
Publishing complete.**

This showed up after I entered this one 
`php artisan vendor:publish --provider="Kreait\Laravel\Firebase\ServiceProvider" --tag=config`

Prior to it, I entered this:
`composer require kreait/laravel-firebase`

I also tried this one below
`<?php
// config/app.php
return [
    // ...
    'providers' => [
        // ...
        Kreait\Laravel\Firebase\ServiceProvider::class
    ]
    // ...   
];`

but is getting this error instead after publishing the service.
**In ProviderRepository.php line 208:
                                                             
  Class 'Kreait\Laravel\Firebase\ServiceProvider' not found**  
                                                             
I tried to look for the solution in google but can't find someone having the same problem using Kreait.

I'm using PHPv 7.3 and Laravel v7.4.

Thanks in advance

**Comment by jeromegamez** [comment]
I'm unfortunately not able to reproduce this issue. What I did to try was:

```bash
$ laravel new test
$ cd test
$ composer require kreait/laravel-firebase
$ php artisan vendor:publish --provider="Kreait\Laravel\Firebase\ServiceProvider" --tag=config
👇
Copied File [/vendor/kreait/laravel-firebase/config/firebase.php] To [/config/firebase.php]
Publishing complete.
```

and it worked 🤔. Could you please try the same?

**Comment by benjnp** [comment]
Well that worked. The only thing different with what I did was. 

composer create-project --prefer-dist laravel/laravel test

But anyway, I tried it again using the prefer-dist option and it definitely worked. Thanks
