### ISSUE TITLE
Custom Client

### ISSUE THREAD

**Issue by lvandyk** [kreait/laravel-firebase#34]
Is it possible to create a custom client with different credentials?

I would like to store multiple Firebase credentials and instantiate a different client depending on business logic. 

Scenario:

Send push notification to APP X using Credentials X and then send push notification to APP Y using Credentials Y.

Am I better off just constructing the cURL myself?

**Comment by jeromegamez** [comment]
The package supports only one Firebase project out of the box, but if you look into the service provider, you‘ll see that there is not much complicated logic going on there.

I would recommend using the underlying SDK (https://github.com/kreait/firebase-php) to create your multiproject structure

```php
use Kreait\Firebase\Factory;

$projectA = (new Factory())->withServiceAccount('/path/to/project-a-serviceaccount.json');

$projectB = (new Factory())->withServiceAccount('/path/to/project-b-serviceaccount.json');

$messagingForProjectA = $projectA->createMessaging();

$messagingForProjectB = $projectB->createMessaging();
```

but that’s of course a biased recommendation :). going with bare curl requests though... that I wouldn‘t do. At least use https://github.com/googleapis/google-auth-library-php

**Comment by lvandyk** [comment]
@jeromegamez Thank you for the feedback and suggestion!

**Comment by nicolasvahidzein** [comment]
Hello, i realized this is what i am currently in need of. @lvandyk were you able to implement this?
