### ISSUE TITLE
where is the noitification sound

### ISSUE THREAD

**Issue by RolandVerner** [kreait/laravel-firebase#35]
How i can set noitifications sound i cont find it

**Comment by jeromegamez** [comment]
That's a platform specific configuration of which you can find the documentation here: https://firebase-php.readthedocs.io/en/stable/cloud-messaging.html#adding-target-platform-specific-configuration

Depending on your target platform, you can then find the payload reference at https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidconfig (Android) or https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943363 (Apple)

In both, the field name is `sound`.
