### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by jaypee888** [kreait/laravel-firebase#37]
Hi, 

I tried to install this package but it cause me out of memory. I already change the size of my memory_limit in php to -1 but still I've got this error. Please let me know if I miss something before installation. 

$ php artisan --version
Laravel Framework Lumen (5.8.12) (Laravel Components 5.8.*)

Thank you. 

$ composer require kreait/laravel-firebase
Using version ^2.0 for kreait/laravel-firebase
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

VirtualAlloc() failed: [0x00000008] Not enough memory resources are available to process this command.

VirtualFree() failed: [0x000001e7] Attempt to access invalid address.

VirtualAlloc() failed: [0x00000008] Not enough memory resources are available to process this command.

VirtualFree() failed: [0x000001e7] Attempt to access invalid address.

PHP Fatal error:  Out of memory (allocated 918552576) (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Fatal error: Out of memory (allocated 918552576) (tried to allocate 4096 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52.

**Comment by nv-trung** [comment]
try this 
COMPOSER_MEMORY_LIMIT=-1 composer require kreait/laravel-firebase

**Comment by wangjacsi** [comment]
I got the same issue, any pc(mac pro, imac, another mac pro) could n't install this.

**Comment by jeromegamez** [comment]
@wangjacsi Please see https://github.com/kreait/laravel-firebase/issues/37#issuecomment-633453189 for the solution and https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more general information.
