### ISSUE TITLE
Adding Data, outside the data[]

### ISSUE THREAD

**Issue by audetcameron** [kreait/laravel-firebase#38]
Our app developer is asking for content_available:true to be outside of the ->withData() array.  Is there a way to do this or should we create a raw message array?

**Comment by jeromegamez** [comment]
`content_available` is a payload key that's only available in FCM's [legacy HTTP  Protocol](https://firebase.google.com/docs/cloud-messaging/http-server-ref) - the SDK uses the [V1 API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages), where `content_available` doesn't seem to exist
