### ISSUE TITLE
Adding to the factory?

### ISSUE THREAD

**Issue by audetcameron** [kreait/laravel-firebase#39]
In the php docs it talks about adding withEnabledDebug() to the factory, is there a way to do this in the laravel wrapper?

**Comment by jeromegamez** [comment]
Not yet, but there will be a way shortly 😅

**Comment by jeromegamez** [comment]
Here it is 🥳 [2.1.0](https://github.com/kreait/laravel-firebase/releases/tag/2.1.0)

**Comment by audetcameron** [comment]
> Here it is 🥳 [2.1.0](https://github.com/kreait/laravel-firebase/releases/tag/2.1.0)

very speedy :) thanks
