### ISSUE TITLE
Prefer/Must use Facade notice in documentation

### ISSUE THREAD

**Issue by JonathanGuo** [kreait/laravel-firebase#4]
I think the documentation needs to be more clear to Laravel devs for using Facades instead of creating `Kreait\Firebase\Factory`.

I've encountered a caching issue by following the documentation. What I've done is created a `Kreait\Firebase\Factory` instance and create dynamic links.

Example:
```php
(new \Kreait\Firebase\Factory())
            ->createDynamicLinksService($domain)
            ->createDynamicLink($url, $type);
```

It's working fine at my local since I don't cache my config at my local. But when I go live, this code doesn't work any more because the production runs `php artisan config:cache`. The Factory tries to resolve credentials through `FromEnvironmentVariable::getValueFromEnvironment()`. However the `$_ENV` is empty since I cached. If I want to use the code above I must create a `ServiceAccount` and attach it to the factory by `withServiceAccount()` method, and turn off auto discovery.

By switching to facade and then it works, which makes sense because it's facade instance is using the cached config.

```php
FirebaseDynamicLinks::createDynamicLink($url, $type);
```

This library is awesome. I think the documentation could be better to remind Laravel developers **MUST/PREFER** using Facade to auto-discovery the service provider.

**Comment by jeromegamez** [comment]
Thank you for letting me know, the documentation really is not clear about that (the SDK docs only refer to the SDK, not its integration).

Until I figure out better documentation on the main package, would perhaps a note in the Laravel package's README help? I was thinking about something like this in the _Usage_ section:

> **You don't need and should not use the `new Factory()` pattern described in the SDK documentation, this is already done through the Service Provider of this package. Always use Dependency Injection, the Facades or the `app()` helper.**

What do you think?

**Comment by JonathanGuo** [comment]
> Thank you for letting me know, the documentation really is not clear about that (the SDK docs only refer to the SDK, not its integration).
> 
> Until I figure out better documentation on the main package, would perhaps a note in the Laravel package's README help? I was thinking about something like this in the _Usage_ section:
> 
> > **You don't need and should not use the `new Factory()` pattern described in the SDK documentation, this is already done through the Service Provider of this package. Always use Dependency Injection, the Facades or the `app()` helper, otherwise the package configuration has no effect.**
> 
> What do you think?

Brilliant! That makes more sense to devs. Thanks. 👍

**Comment by jeromegamez** [comment]
Added with bd90a20fb317586e9d8f45af2eb8263ff5819587, thanks again! 🌺
