### ISSUE TITLE
can you put implementing for this library 

### ISSUE THREAD

**Issue by thaifani** [kreait/laravel-firebase#42]
Hi 
please provide an example for using this extra lib

**Comment by jeromegamez** [comment]
An example to do what? The package in its current form is just a wrapper for the SDK to make the configuration easier.

**Comment by thaifani** [comment]
but i have receive this error
we failsKreait\Firebase\Exception\InvalidArgumentException: Invalid service account specification in 

...
...
"message":"Invalid service account specification

**Comment by jeromegamez** [comment]
That’s probably because you used a configuration for a web client SDK instead of a Service Account. The setup/configuration is described in the readme of this repo: https://github.com/kreait/laravel-firebase#configuration

**Comment by thaifani** [comment]
thanks a lot 
it was because the json file was in incorrect dir

**Comment by jeromegamez** [comment]
You're welcome 🌺
