### ISSUE TITLE
Is there any demo for Sync firestore/firebase data to laravel eloquent model

### ISSUE THREAD

**Issue by vivekp56** [kreait/laravel-firebase#44]
Hi,

Can you please provide any route/model binding and sync firebase/firestore data to laravel eloquent model?
Purpose is I can used all the Laravel functionality with the firebase/firestore and used it in development.

Please give response to this questions, is there any way we can go forward with this?

Thank You,
Vivek

**Comment by jeromegamez** [comment]
There are currently no plans to provide this feature. You could have a look at https://github.com/mpociot/laravel-firebase-sync or similar projects as an inspiration to implement this in your application.

**Comment by chrillep** [comment]
found these two packages for using firebase realtime db with models (not tested)
* https://github.com/plokko/laravel-firebase
* https://github.com/EverthSarantes/laravel-firebase-models

Im looking into it since im using filament and all packages want to steer you into using data through models :)
