### ISSUE TITLE
Manage multiple Firebase configurations within one Laravel app

### ISSUE THREAD

**Issue by Hillcow** [kreait/laravel-firebase#47]
Hey there,

for my current project I need the ability to send FCM to hundreds of different apps. However, as far as I can see there is no way to do so with this package, because you can only set one single configuration?

Using the Firebase admin SDK for PHP, it works like this:

`$factory = (new Factory)->withServiceAccount('/path/to/firebase_credentials.json');`

Take this as a feature request then, thanks!

**Comment by jeromegamez** [comment]
You're right, at the moment you can only use one Firebase project with the package - it's on my bucket list, but unfortunately, I can't give you an ETA on when I will be able to get to it, and there are a couple of challenges to make it work with Facades and multiple aliases. Thank you for taking the time to tell me that there's an actual need for this!

**Comment by Hillcow** [comment]
I see. So for the moment I have to fallback to the standard Firebase admin SDK for PHP with my Laravel app, right?

Actually I don't even need this feature right now, but I will need it in like 2 months time. Just to let you know, some motiviation 😄 Thank you!

**Comment by sooxt98** [comment]
Same here, is there any workaround for this issue? i tried to google but still not sure how to deal with dynamic firebase json config in service provider; I'm planning to store the json into the database, i just need some guide :3

**Comment by jeromegamez** [comment]
The package is indeed just a wrapper, but with helpers that make dependency injection and working "the Laravel way" easier (Facades, Aliases).

It's a general purpose package that is enough for the majority of projects - if you have special requirements (like, at the moment, access to multiple Firebase projects inside one backend application) you're far better off implementing this specifically for your application yourself. The advantage of the current package is that it's easy to set up: one environment variable and you're basically set. This structure would not be well-maintainable with multiple projects.

My recommendation: look at the ServiceProvider of this package to see how it configured the underlying SDK and re-implement it - dynamic configuration with different credentials is far in the future of this package - if it comes at all 🙈
