### ISSUE TITLE
DUPLICATE_LOCAL_ID

### ISSUE THREAD

**Issue by vdhruv** [kreait/laravel-firebase#49]
After installing package, i setup admin config file in .env file,

but when i run my application,

![image](https://user-images.githubusercontent.com/35102375/88700588-88110280-d126-11ea-8244-b00929c67468.png)

i am facing this issue.

**Comment by jeromegamez** [comment]
Unfortunately this is not enough information for me to help you. Please provide more details on what you are trying to implement and the code you used 🙏

**Comment by vdhruv** [comment]
i did solve this issue,
i was creating authentication user using API and i was passing duplicate identifier(parameter) for multiple users so that is the reason i was getting this error.

i checked the source code and figure it out.

Thank you for helping.
