### ISSUE TITLE
Permission denied on subscription

### ISSUE THREAD

**Issue by Waqaralipk** [kreait/laravel-firebase#5]
`Can` you please let me know on subscription why I am getting permission denied error. While I am using Facades now instead of the factory. 
Here is an example of a sample code that I am using. Correct me if I am doing something wrong.
I have assigned false validation rule on firebase because authentication is required there and how can I do authentication to using the admin-firebase laravel package. However, I didn't do any authentication when using a factory and it was working. One another thing, do we have support to use [understand-delivery](https://firebase.google.com/docs/cloud-messaging/understand-delivery) with that package? 

Code:
```
use FirebaseMessaging, FirebaseDatabase;
FirebaseMessaging::unsubscribeFromTopic($topic, $tokensArray);
```

here is the snap of error  
![Screenshot from 2019-12-17 12-35-28](https://user-images.githubusercontent.com/39183708/70975097-11f5e900-20cb-11ea-9da6-bd4399bbfd54.png)

**Comment by jeromegamez** [comment]
Could you please update the issue? You posted almost everything in the title. Please also format your code example. There is no need to `@` me, I get notified about each comment.

That being said...

Have you configured the package and are you using the correct service account?

Do other operations work, or is it just this one?

**Comment by Waqaralipk** [comment]
> Could you please update the issue? You posted almost everything in the title. Please also format your code example. There is no need to `@` me, I get notified about each comment.
> 
> That being said...
> 
> Have you configured the package and are you using the correct service account?
> 
> Do other operations work, or is it just this one?

sure let me update

**Comment by Waqaralipk** [comment]
> Could you please update the issue? Your code formatting makes it really difficult to read. Please also format your code example. There is no need to `@` me, I get notified about each comment.
> 
> That being said...
> 
> Have you configured the package and are you using the correct service account?
> 
> Do other operations work, or is it just this one?

Yes, I have configured. The same service account was using before with the factory and it was working fine.

**Comment by jeromegamez** [comment]
The operation itself worked (that's why you get two results) - permission denied in this case means that the two tokens don't belong to the Firebase project of the Service Account.

**Comment by Waqaralipk** [comment]
> The operation itself worked (that's why you get two results) - permission denied in this case means that the two tokens don't belong to the Firebase project of the Service Account.

Sounds good to me, it might be possible because I am testing from the local environment. What about [understand-delivery](https://firebase.google.com/docs/cloud-messaging/understand-delivery)
can we use this delivery feature with this Laravel-firebase package?

**Comment by jeromegamez** [comment]
You can enable message delivery exports on a global and app-instance level by following https://firebase.google.com/docs/cloud-messaging/understand-delivery#bigquery-data-export - access to BigQuery to fetch this data is not part of the package or the SDK. I hope I'm understanding you correctly.

**Comment by Waqaralipk** [comment]
Okay thank you so much for your precious time

**Comment by jeromegamez** [comment]
You‘re welcome 🌺

**Comment by Waqaralipk** [comment]
Is it possible to get bigquery-data-export data using PHP admin SDK? or we use for it 
Google BigQuery?
