### ISSUE TITLE
Implement Test with FirebaseFactory.

### ISSUE THREAD

**Issue by mahdyaslami** [kreait/laravel-firebase#53]
I Searched in [kreait\firebase-php](https://github.com/kreait/firebase-php) package i found it use `Kreait\Firebase\Factory` in `IntegerationTestCase` class and used it to test. ([For example test `subscriteToTopic` method in `FirebaseMessaging` class](https://github.com/kreait/firebase-php/blob/main/tests/Integration/Messaging/AppInstanceTest.php#L36)).

Is it possible to adding `fake` method to `FirebaseMessaging` facade and other facades for mocking and used it in test like `MailFake` class in laravel.

Example change in `FirebaseMessaging` facade:

```php
/**
 * @see \Kreait\Firebase\Messaging
 */
final class FirebaseMessaging extends Facade
{
    /**
     * Replace the bound instance with a fake.
     *
     * @return \Illuminate\Support\Testing\Fakes\MailFake
     */
    public static function fake()
    {
        static::swap($fake = (new FirebaseFactory())->createMessaging());

        return $fake;
    }

    protected static function getFacadeAccessor()
    {
        return 'firebase.messaging';
    }
}
```

Example test for an API:

```php
/** @test */
public function subscribe_temp_topic()
{
    FirebaseMessaging::fake();

    $body = [
        'topic' => 'temp',
        'fcmToken' => 'token'
    ];

    $this->post('/subscribe', $body, $this->defaultHeaders)
        ->seeStatusCode(200)
        ->seeJsonContains([
            "results" => [[]]
        ]);
}
```

I test and it work prefect. Is it good way for creating test??

**Comment by jeromegamez** [comment]
Hey, and sorry for the late reply! I haven't really worked with Laravel's fakes in the past, so I understand the principle, but could you please explain a little more in detail how `$fake = (new FirebaseFactory())->createMessaging()` is a _fake_? For me it looks as if this still creates the Messaging component from an uncounfigured Factory (and so would still make "real" requests to the Firebase APIs... 🤔
