### ISSUE TITLE
AdditionalUserInfo to Appear in UserRecord

### ISSUE THREAD

**Issue by zerubabbel** [kreait/laravel-firebase#54]
Hello,

I'm trying to get the additionalUserInfo object, in order to retrieve twitter username, to appear in the UserRecord using  $this->auth->getUser($uid), and can't seem to find any way to do this. Is it possible with this package? 

Thank so much, your help is greatly appreciated.

**Comment by jeromegamez** [comment]
Sorry for taking so long to reply. If this is still relevant, please open a new issue. I'm not sure what you mean with "the additionalUserInfo object", but you can see what the `UserRecord` contains at https://firebase-php.readthedocs.io/en/5.x/user-management.html#user-records / https://github.com/kreait/firebase-php/blob/5.x/src/Firebase/Auth/UserRecord.php . The `providerData` should include information about a user on other platforms.
