### ISSUE TITLE
Kreait\Firebase\Exception\Database\ApiConnectionFailed

### ISSUE THREAD

**Issue by shouvick** [kreait/laravel-firebase#55]
I am getting this error. previously it's working fine. I am using a firebase realtime database

Kreait\Firebase\Exception\Database\ApiConnectionFailed Unable to connect to the API: Connection refused for URI https://oauth2.googleapis.com/token

what is the possible problem?

**Comment by jeromegamez** [comment]
Duplicate of https://github.com/kreait/firebase-php/issues/466
