### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by henrydennis-sonin** [kreait/laravel-firebase#58]
With Laravel 8 being released shortly, it's probably time to update. Not sure about Lumen compatibility as it doesn't seem to have an 8.x branch yet. Lumen installer is confirmed as abandoned.

**Comment by carloshc** [comment]
Is `kreait/firebase-php ^4.3` incompatible with `guzzlehttp/guzzle ^7.0.1` ?

**Comment by jeromegamez** [comment]
@carloshc As mentioned in the issue you opened in the SDK's repo: no, it shouldn't have a problem with a newer Guzzle version ☺️.

@henrydennis-sonin I have a local Branch for Laravel 8 support on my computer since quite some time now, I'll test and merge it soon 🤞

**Comment by jeromegamez** [comment]
Heads up: [laravel/lumen-framework](https://packagist.org/packages/laravel/lumen-framework) has not yet been released as 8.0 yet. It's dev dependency required for the package tests - I'm working on a workaround.

**Comment by jeromegamez** [comment]
Well, this was easy: https://github.com/kreait/laravel-firebase/commit/07852d075d3bb79893af27e3eb8314d574bc0fd9 🤷 😅 

Update your dependencies, the [new release (2.3.0)](https://github.com/kreait/laravel-firebase/releases) is ready 🚀
