### ISSUE TITLE
Use Credentials from .env and not from json

### ISSUE THREAD

**Issue by Jannnnnn** [kreait/laravel-firebase#63]
Is it possible to get the firebase service credentials not from a json file but from an environment or as Firebase offers as a server auth token? 

Like here https://github.com/laravel-notification-channels/fcm/tree/v1#setting-up-the-fcm-service

My problem ist that i can easily set environment in my deployment but not a file.

**Comment by jeromegamez** [comment]
While it's not documented on purpose, it's possible with setting the environment variable `FIREBASE_CREDENTIALS` with the minified output of the JSON file. You can create it, for example, with [`jq`](https://stedolan.github.io/jq/) and the following command

```bash
$ jq -c . < /path/to/service_account.json
```

**Comment by Jannnnnn** [comment]
@jeromegamez  thanks for the hint, i could have guessed that too.
I put the content of the service_account.json to that environment. Works like a charm!
