### ISSUE TITLE
click_action does not work

### ISSUE THREAD

**Issue by cindyadonia** [kreait/laravel-firebase#64]
Hello there, i'm developing a REST API, and trying to send cloud message with click_action inside the notification array.
I did receive my notification, but it doesn't redirect me to the url when I click on it.

I dont find anything wrong with the array that I sent.

```
$message = CloudMessage::fromArray([
            'token' => $deviceToken,
            'notification' => [
                'title' => 'You just logged in!',
                'body' => 'If this is not you! Please report to our cs.',
                'click_action' => 'https://www.example.com/'
            ]
        ]);

$this->messaging->send($message);
```

I was wondering if anyone experiencing this issue as well.
I've tried triggering this raw using my postman with my firebase key, and the click_action works fine.

**Comment by jeromegamez** [comment]
If the action is not working in a browser app, please have a look at https://github.com/firebase/quickstart-js/issues/209#issuecomment-384952093 

If it's on Android, please check https://stackoverflow.com/a/47908598 and https://stackoverflow.com/questions/43372117/fcm-notification-click-action-not-working/43383425

In other issues for the SDK, it sometimes helped to put values in double quotes `"` instead of single quotes `'` (although I admit that I don't know why this _should_ help 😅)

Unfortunately, from this SDK's perspective, all we can do is send a message and rely on the Firebase API to deliver it. If an option is invalid, the API will reject the message, if it accepts it, from our perspective, everything should be "fine".

I hope to be wrong, I would prefer that it's a bug in the SDK because then I can fix it - if you find out what might be going wrong, please let me know 🙏

**Comment by cindyadonia** [comment]
Thank you, i've checked the issue mentioned for browser app. I didn't find anything that actually will helps.
I also tried the double quotes, and it is still not working somehow.
I didn't receive any error response from the Firebase API anyway, which is really weird.

May i know if you ever tried to use click_action before? and how do you do it if it actually works?

**Comment by cindyadonia** [comment]
I didn't manage to find how to make it works, I just leave the package and make my own service for the FCM right now.
If there is an update on how to solve this issue, I would be glad to re-open this issue again.

**Comment by jeromegamez** [comment]
https://github.com/kreait/firebase-php/issues/446#issuecomment-653326134 described how they got it working on Android.

Looking at https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidnotification it seems that `click_action` is natively supported only on Android.

https://github.com/firebase/quickstart-js/issues/209#issuecomment-384952093 suggests that `click_action` can be handled for WebPush notifications by the Firebase JS Client SDK.

I am only able to test WebPush notifications, but I can confirm that the `click_action` field arrives at its destination:

```php
$message = CloudMessage::fromArray([
    'token' => $token,
    'notification' => [
        'title' => 'Notification title',
        'body' => 'Notification body',
    ],
    'data' => [
        'click_action' => 'https://firebase.google.com?data',
        'meta' => 'root data',
    ],
    'android' => [
        'notification' => [
            'title' => 'Android title',
            'body' => 'Android body',
            'click_action' => 'https://firebase.google.com?android',
        ],
        'data' => [
            'meta' => 'android data',
            'click_action' => 'https://firebase.google.com?android_data',
        ],
    ],
    'webpush' => [
        'notification' => [
            'title' => 'Webpush title',
            'body' => 'Webpush body',
            'click_action' => 'https://firebase.google.com?webpush_notification',
        ],
        'data' => [
            'click_action' => 'https://firebase.google.com?webpush_data',
            'meta' => 'webpush data',
        ],
    ],
]);

$messaging->send($message);
```

![image](https://user-images.githubusercontent.com/67554/96791653-1bda2e00-13f9-11eb-8810-c39a8ccfc795.png)

**Comment by zikezhang** [comment]
Hi @jeromegamez ,

![call_action](https://user-images.githubusercontent.com/5647317/116750106-f5143a00-a9cf-11eb-8894-e2111a7f7eeb.jpg)


browser got the response from the registered service worker.
But `click_action` is still not working when you click the notification message. on any browsers.

**Comment by jeromegamez** [comment]
I'm afraid I don't have the competence to help you with that though, this is an (Backend) Admin SDK after all 😅

Can perhaps the service worker trigger a browser open? If not through the click action, perhaps you could send the target URL in the data payload and trigger it manually? Just thinking out loud, no idea if this can work
