### ISSUE TITLE
Firebase project [myproject] not configured.

### ISSUE THREAD

**Issue by virenderscideas** [kreait/laravel-firebase#70]
Hello,

I am getting this error "Firebase project [myproject] not configured." while sending a notification in laravel with FirebaseChannel.
    public function via($notifiable)
    {
        return [FirebaseChannel::class];
    }

it's probably generated from this file but don't know what i did wrong.

vendor/kreait/laravel-firebase/src/FirebaseProjectManager.php:41

protected function configuration(string $name): array
    {
        $config = $this->app->config->get('firebase.projects.'.$name) ?? null;
        if (!$config) {
            throw new InvalidArgumentException("Firebase project [{$name}] not configured.");
        }
         return $config;
    }

**Comment by jeromegamez** [comment]
Hey @virenderscideas, FYI I moved this issue from the firebase-php repo here. How have you configured the package? Which versions of the kreait packages are you using (`composer show | grep kreait`)? On which PHP version? Is this something that worked before but stopped working?

**Comment by adityaa-dev** [comment]
i'm facing the same issue
Below is the composer show
![image](https://user-images.githubusercontent.com/26678129/101463291-3f364980-3963-11eb-9081-f468e204c65f.png)

**Comment by adityaa-dev** [comment]
what is the right way to configure firebase in laravel? all the tutorials and articles are outdated and there's no recent specific laravel based articles.
Thanks in Advance

**Comment by jeromegamez** [comment]
Have you put a `FIREBASE_CREDENTIALS=/path/to/your/service_account.json` line in your `.env` file?

**Comment by adityaa-dev** [comment]
Its in my project root directory ![image](https://user-images.githubusercontent.com/26678129/101466826-950cf080-3967-11eb-8685-c6880a4c85ba.png)

**Comment by jeromegamez** [comment]
Sorry for the late reply - have you resolved the issue in the meantime? If not, could you please share the full contents of `config/firebase.php`?

**Comment by denzkiuy** [comment]
I'm having the same issue, it's my first time trying firebase and this package. I have placed the service account json in the .env file as well. I haven't touched the firebase.php configuration.

**Comment by jeromegamez** [comment]
I just realized that `FirebaseChannel` seems to be a class from https://github.com/laravel-notification-channels/ - could this perhaps be an error that's triggered from there?

Either way, it would be nice if you could show me some reproducible code that I can use to test this - in my local tests, everything seems to work just fine, and I would be happy if it's a bug in the package, because then I can fix it 🤞

**Comment by denzkiuy** [comment]
In my case i didn't use FirebaseChannel, I'm still new to fire base so i just followed the [documentation of the Firebase PHP Admin SDK](https://firebase-php.readthedocs.io/)

`
use Kreait\Firebase\Messaging\CloudMessage;
use Kreait\Firebase\Messaging\Notification;

$topic = 'topic';
        $title = 'Title';
        $body = 'Body';

        $messaging = app('firebase.messaging');

        $notification = Notification::create($title, $body);

        $message = CloudMessage::withTarget('topic', $topic)
            ->withNotification($notification) // optional
            ->withData($data) // optional
        ;

        $messaging->send($message);`

**Comment by denzkiuy** [comment]
Also, I tried not putting the FIREBASE_CREDENTIALS into the .env file to find out what error it'll give me. And it's the same error.

**Comment by jeromegamez** [comment]
I just tried in my test-laravel project and I'm sorry I can't confirm the problem. What wonders me is that you get the error names `myproject` as a project - if no other configuration is present, the default project is referenced as `app`. 🤔 

Which Laravel and PHP version are you using? What happens when, instead of `app('firebase.messaging')` you try 

```php
use Kreait\Laravel\Firebase\Facades\Firebase;

// ...

$messaging = Firebase::messaging();
```

?

Just to be sure, please share the output of these commands in your terminal:

```sh
$ php -v
$ composer show
```

**Comment by denzkiuy** [comment]
I think I found my mistake. I actually specified the project name in the env file `FIREBASE_PROJECT` thinking that this will only let me specify the "Name" of the firebase project. Looking at the firebase.php config file I think I realize how it works now. 

Thank you so much @jeromegamez for the very quick response!!

**Comment by jeromegamez** [comment]
Glad I could help, I hope the package can serve you well from here on! 🌺

**Comment by Prakort** [comment]
I had the same issue but running `php artisan config:cache` fixed the issue.

**Comment by faizanmuzaffar12** [comment]
Hello Everyone, I was just implementing the Laravel Firebase, 

I am having confusion issue that what will be the firebase project, is it the title of the project ? or the project id from the credentials.json?

because I am having the same issue that 

The Firebase project [Rehbr-App] is not configured.

![image](https://github.com/kreait/laravel-firebase/assets/45538083/f3896d20-4d14-4728-a7c5-ffeb0016b45e)

**Comment by jeromegamez** [comment]
Yes, it's the project ID from credentials file

**Comment by nehabvm23** [comment]
hii, I am having the same issue, i run the above mentioned commands also, but not worked..

**Comment by liza-nt** [comment]
adding FIREBASE_PROJECT in .env still did not work for me

**Comment by jeromegamez** [comment]
@liza-nt This issue is three years old 😅

**Comment by jPrudence** [comment]
The value of `FIREBASE_PROJECT` must correspond to one of the projects listed under the `projects` key in the `firebase.php` configuration file.  
If you set a specific value for `FIREBASE_PROJECT` in your `.env` file, you must also add the corresponding configuration in the `projects` section of the `firebase.php` file.  

To avoid any configuration errors, it is generally better **not to manually define `FIREBASE_PROJECT` in the `.env` file**, and **not to directly modify the default value of `env('FIREBASE_PROJECT')` in `firebase.php` without fully understanding the impact**, unless you properly add the necessary configurations.


<img width="954" height="592" alt="Image" src="https://github.com/user-attachments/assets/5eb6a83a-fbda-4785-943f-bb3103f4c9c0" />
