### ISSUE TITLE
Dependency version Issue

### ISSUE THREAD

**Issue by ubxtyrav** [kreait/laravel-firebase#72]
- kreait/firebase-php[dev-main, 5.12.0] require lcobucci/jwt ^3.4.1 -> found lcobucci/jwt[3.4.1, 3.4.x-dev] but the package is fixed to 4.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/firebase-php 5.11.0 requires lcobucci/jwt ^3.3.1 -> found lcobucci/jwt[3.3.1, ..., 3.4.x-dev] but the package is fixed to 4.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/laravel-firebase 3.0.0 requires kreait/firebase-php ^5.11.0 -> satisfiable by kreait/firebase-php[5.11.0, 5.12.0, 5.x-dev (alias of dev-main)].
    - kreait/firebase-php 5.x-dev is an alias of kreait/firebase-php dev-main and thus requires it to be installed too.
    - Root composer.json requires kreait/laravel-firebase ^3.0 -> satisfiable by kreait/laravel-firebase[3.0.0].

**Comment by jeromegamez** [comment]
As mentioned in Discord, this will be solved when https://github.com/kreait/firebase-php/pull/509 is merged. Until then only lcobucci/jwt 3.x is supported.

**Comment by jeromegamez** [comment]
Better late than never: since kreait/firebase-php#509 has been merged, this should now be resolved. 🥳
