### ISSUE TITLE
Kreait\Firebase\Exception\RuntimeException with message 'Unable to create a FirestoreClient: Class 'Google\Cloud\Firestore\FirestoreClient' not found'

### ISSUE THREAD

**Issue by habib-eg** [kreait/laravel-firebase#73]
![Screenshot from 2020-12-24 15-17-35](https://user-images.githubusercontent.com/25707838/103091019-7d866680-45fb-11eb-855a-7617cda6d586.png)
![Screenshot from 2020-12-24 15-19-04](https://user-images.githubusercontent.com/25707838/103091022-7f502a00-45fb-11eb-8bf6-0e2981b01b50.png)

**Comment by jeromegamez** [comment]
https://firebase-php.readthedocs.io/en/5.14.0/cloud-firestore.html

**Comment by habib-eg** [comment]
do have idea with this error ?
- google/cloud-firestore v1.19.0 requires ext-grpc * -> it is missing from your system. Install or enable PHP's grpc extension.

**Comment by jeromegamez** [comment]
https://cloud.google.com/php/grpc
