### ISSUE TITLE
Error Curl Ssl in RequestWrapper.php

### ISSUE THREAD

**Issue by danielpinon** [kreait/laravel-firebase#75]
Error: 
- cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
- Google\Cloud\Core\Exception\ServiceException
For this error there should be an option in the config where you choose to ignore or leave the option active. Thanks!

**Comment by danielpinon** [comment]
|  
-- | --
message | "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"
exception | "Google\\Cloud\\Core\\Exception\\ServiceException"
file | "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\google\\cloud-core\\src\\RequestWrapper.php"
line | 368
trace | [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
0 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\google\\cloud-core\\src\\RequestWrapper.php", line: 207, function: "convertToGoogleException", … }
1 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\google\\cloud-core\\src\\Upload\\MultipartUploader.php", line: 44, function: "send", … }
2 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\google\\cloud-storage\\src\\Bucket.php", line: 294, function: "upload", … }
3 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\app\\Http\\Controllers\\IndicacoesController.php", line: 244, function: "upload", … }
4 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php", line: 54, function: "sendPdf", … }
5 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php", line: 45, function: "callAction", … }
6 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php", line: 239, function: "dispatch", … }
7 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php", line: 196, function: "runController", … }
8 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", line: 685, function: "run", … }
9 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 128, function: "Illuminate\\Routing\\{closure}", … }
10 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php", line: 41, function: "Illuminate\\Pipeline\\{closure}", … }
11 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
12 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php", line: 78, function: "Illuminate\\Pipeline\\{closure}", … }
13 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
14 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php", line: 49, function: "Illuminate\\Pipeline\\{closure}", … }
15 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
16 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php", line: 116, function: "Illuminate\\Pipeline\\{closure}", … }
17 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php", line: 62, function: "handleStatefulRequest", … }
18 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
19 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php", line: 37, function: "Illuminate\\Pipeline\\{closure}", … }
20 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
21 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php", line: 67, function: "Illuminate\\Pipeline\\{closure}", … }
22 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
23 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 103, function: "Illuminate\\Pipeline\\{closure}", … }
24 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", line: 687, function: "then", … }
25 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", line: 662, function: "runRouteWithinStack", … }
26 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", line: 628, function: "runRoute", … }
27 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php", line: 617, function: "dispatchToRoute", … }
28 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", line: 165, function: "dispatch", … }
29 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 128, function: "Illuminate\\Foundation\\Http\\{closure}", … }
30 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php", line: 21, function: "Illuminate\\Pipeline\\{closure}", … }
31 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
32 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php", line: 21, function: "Illuminate\\Pipeline\\{closure}", … }
33 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
34 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php", line: 27, function: "Illuminate\\Pipeline\\{closure}", … }
35 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
36 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php", line: 63, function: "Illuminate\\Pipeline\\{closure}", … }
37 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
38 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php", line: 37, function: "Illuminate\\Pipeline\\{closure}", … }
39 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
40 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\fideloper\\proxy\\src\\TrustProxies.php", line: 57, function: "Illuminate\\Pipeline\\{closure}", … }
41 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 167, function: "handle", … }
42 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php", line: 103, function: "Illuminate\\Pipeline\\{closure}", … }
43 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", line: 140, function: "then", … }
44 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php", line: 109, function: "sendRequestThroughRouter", … }
45 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\public\\index.php", line: 55, function: "handle", … }
46 | Object { file: "C:\\Users\\A1\\Documents\\DESENVOLVIMENTO\\GITHUB\\DENTALIZE\\Dentalize.Site\\server.php", line: 21, function: "require_once" }

**Comment by jeromegamez** [comment]
If you have cURL errors, please refer to https://firebase-php.readthedocs.io/en/5.14.1/troubleshooting.html#curl-error-xx

I'm not sure what you mean by "an option in the config where you choose to ignore or leave the option active", but if this involves somehow ignoring SSL errors... I will not 😓
