### ISSUE TITLE
Kreait\Firebase\Exception\Database\DatabaseError 404 Not Found 

### ISSUE THREAD

**Issue by jewel-rana** [kreait/laravel-firebase#77]
Hello, I need help. I have configured firebase project successfully when I try to create or read data I got this error, I am using verion 3.0
Kreait\Firebase\Exception\Database\DatabaseError
404 Not Found
http://localhost:8000/admin/firebase 

Kreait\Firebase\Exception\DatabaseApiExceptionConverter::convertGuzzleRequestException
vendor/kreait/firebase-php/src/Firebase/Exception/DatabaseApiExceptionConverter.php:62

**Comment by jeromegamez** [comment]
You probably need to define the Database URL for your Realtime Database, either with the environment variable `FIREBASE_DATABASE_URL` or by publishing the config of the package.

More information: https://github.com/kreait/firebase-php/discussions/545#discussioncomment-275084

**Comment by alanreji** [comment]
I added FIREBASE_DATABASE_URL to .env and that solved the problem.

The documentation at [https://github.com/kreait/laravel-firebase#configuration](https://github.com/kreait/laravel-firebase#configuration) doesn't mention this step.

**Comment by jeromegamez** [comment]
This is [now included](https://github.com/kreait/laravel-firebase/commit/4fa91e556218358e62731a7d0d85e165b2b01807) in the [README](https://github.com/kreait/laravel-firebase#configuration).
