### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by chimit** [kreait/laravel-firebase#8]
Please, add Lumen compatibility.

```
[2020-01-07 03:24:04] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Kreait\Laravel\Firebase\ServiceProvider::Kreait\Laravel\Firebase\{closure}() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given, called in /home/vagrant/code/api/vendor/illuminate/container/Container.php on line 791 in /home/vagrant/code/api/vendor/kreait/laravel-firebase/src/ServiceProvider.php:83
```

**Comment by jeromegamez** [comment]
Hi @chimit, thank you for bringing this up! Could you please test if adding/replacing

```
"kreait/laravel-firebase": "dev-lumen-support as 1.2.1",
```

to/in your composer.json and then updating fixes the issue for you? If so, I will merge the change and create a new release.

**Comment by chimit** [comment]
Factory DI works, but Messaging not:

```php
use Kreait\Firebase\Messaging;

function __construct(Messaging $messaging)
{
```

```
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Kreait\Laravel\Firebase\ServiceProvider::Kreait\Laravel\Firebase\{closure}() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given, called
```

Apparently, need to remove type hinting everywhere from the `ServiceProvider.php`.

**Comment by jeromegamez** [comment]
Yes apparently 😉, I should have scrolled down the code more 😅.

Could you please update the dependency and try again?

**Comment by dbaranoff** [comment]
Hey there!

First, thanks for this library - it is awesome!

Second, the pain...

I'm new to Laravel and I've encountered an issue with the Lumen install too.
I set up and installed a fresh version of the package as you said above => `"kreait/laravel-firebase": "dev-lumen-support as 1.2.1"`,

Here's the error when I'm trying to run `php artisan serve`

```
In ServiceProvider.php line 16:
                                                                    
Call to undefined method Laravel\Lumen\Application::configPath() 
```

I suppose it's related to the error above as well?

I'll provide some info below, is it enough?

Please assist - what am I doing wrong?

**Side notes:**
1. Here are some parts of  my `bootstrap/app.php`:

```
...

$app->withFacades(
    true,
    [
        ...
        Kreait\Laravel\Firebase\Facades\FirebaseDatabase::class => 'FirebaseDatabase',
        ...
    ]);

...
$app->configure('firebase'); // was copied manually from vendor/kreait/laravel-firebase/config/firebase.php to config/app.php
...

$app->register(Kreait\Laravel\Firebase\ServiceProvider::class);
...
```

2. Here are versions:
        "laravel/lumen-framework": "^5.8",
        "kreait/laravel-firebase": "dev-lumen-support as 1.2.1",

3, Environment:
        Win10-x64 / OpenServer 5.2.2 / PHP 7.3-x64

4. Tried to run `composer dumpautoload` - no luck.

5. If I don't run `php artisan serve` - it is working as expected - I tested on FirebaseDatabase - the data read and written.

**Comment by jeromegamez** [comment]
@dbaranoff Thanks for letting me know and for providing so much information, I think I can use this to update the documentation and to fix the issues!

I created the #9 PR to make it a little easier to follow along and will mention you there once I have something for you to test if you don't mind 😅
