### ISSUE TITLE
Declaration of Morrislaptop\\Firestore\\Factory::createFirestore(): Morrislaptop\\Firestore\\Firestore must be compatible with Kreait\\Firebase\\Factory::createFirestore

### ISSUE THREAD

**Issue by choudharyafsaralikhurshid** [kreait/laravel-firebase#82]
Please help me i am getting this issue i am using firestore with out grpc extension 
![Screenshot from 2021-03-10 20-16-10](https://user-images.githubusercontent.com/26706193/110784311-8cda8f00-828f-11eb-9746-7e88820f65f8.png)

**Comment by jeromegamez** [comment]
I'm sorry, but I can't provide support for other libraries here 😅 - if you're using Firestore, the Laravel Package and the underlying SDK expect that you have the grpc extension installed and that you use [Google's official Firestore library](https://github.com/googleapis/google-cloud-php-firestore).

You haven't shared which versions of the laravel-firebase package and the SDK you have installed, but you could try using an 1.x release of the package - please note that this will then use a 4.x release of the SDK, and I don't provide free support for releases other than the current ones…
