### ISSUE TITLE
Need Help Install in Laravel 8.0

### ISSUE THREAD

**Issue by daffigusti** [kreait/laravel-firebase#85]
Hello, Please Help to install in Laravel 8.0. 

Get this error when install using this command : 

`composer require kreait/laravel-firebase`

The composer error is : 

`
  Problem 1
    - Installation request for lcobucci/jwt (locked at 3.3.3) -> satisfiable by lcobucci/jwt[3.3.3].
    - kreait/firebase-php 5.14.1 requires kreait/firebase-tokens ^1.14.0 -> satisfiable by kreait/firebase-tokens[1.14.0].
    - kreait/firebase-php 5.15.0 requires kreait/firebase-tokens ^1.14.0 -> satisfiable by kreait/firebase-tokens[1.14.0].
    - kreait/firebase-php 5.16.0 requires kreait/firebase-tokens ^1.14.0 -> satisfiable by kreait/firebase-tokens[1.14.0].
    - kreait/firebase-php 5.17.0 requires kreait/firebase-tokens ^1.14.0 -> satisfiable by kreait/firebase-tokens[1.14.0].
    - kreait/firebase-php 5.x-dev requires kreait/firebase-tokens ^1.14.0 -> satisfiable by kreait/firebase-tokens[1.14.0].
    - Conclusion: don't install kreait/laravel-firebase 3.1.0|install kreait/firebase-tokens 1.14.0
    - Conclusion: don't install kreait/firebase-tokens 1.14.0
    - kreait/laravel-firebase 3.x-dev requires kreait/firebase-php ^5.14.1 -> satisfiable by kreait/firebase-php[5.14.1, 5.15.0, 5.16.0, 5.17.0, 5.x-dev].
    - Installation request for kreait/laravel-firebase ^3.1 -> satisfiable by kreait/laravel-firebase[3.1.0, 3.x-dev].

`

Any Sugestion?

Thanks

**Comment by jeromegamez** [comment]
This is due to the tymon/jwt-auth package preventing the installation of a required dependency. You can read more about it at https://github.com/kreait/firebase-php/discussions/581
