### ISSUE TITLE
Undefined property always whenever tries to use signInWithEmailAndPassword or getUserByEmail

### ISSUE THREAD

**Issue by sakjain02** [kreait/laravel-firebase#88]
If user exist in firebase I am calling $auth->signInWithEmailAndPassword($user->email,$request->password)
and getting this error on login 
"Undefined property: Kreait\Firebase\Auth\SignInResult::$uuid"

Second case when using $auth->getUserByEmail($email)-- Undefined property: Kreait\Firebase\Auth\UserRecord::$uuid"

If user doesn't exist in firebase I am calling $auth->createUserWithEmailAndPassword($user->email, $request->password);
Then it is creating entry successfully.
But the problem is when I sign in 
Package version 3.1 
PHP 7.3
Laravel 8

Thank You

**Comment by jeromegamez** [comment]
`createUser*` and `getUser*` return a `UserRecord` - here you can access the Firebase User ID via the `uid` property, see https://firebase-php.readthedocs.io/en/5.x/user-management.html#user-records

When you **sign in** a user with one of the `signIn*` methods, a `SignInResult` is returned - here you can access the Firebase User Id via the `firebaseUserId()` method, see https://firebase-php.readthedocs.io/en/5.x/authentication.html#custom-authentication-flows

A `uuid` property is exposed nowhere, I wonder why you thought it was 😅

**Comment by sakjain02** [comment]
Thanks for the details. But I am using uid for firebase authentication. Like I am sending entry in the firebase auth and realtime database as well with that I am creating uid node for users and applying rules on it.

**Comment by sakjain02** [comment]
Thank You. For pointing out the mistake I did. 😅
