### ISSUE TITLE
Need help installing package 3.1 with Lumen

### ISSUE THREAD

**Issue by Ceebig** [kreait/laravel-firebase#94]
Good day, I am trying to install the package by running  `composer require kreait/laravel-firebase`, however, this is the error I got and I would appreciate any help to fix it:
`Problem 1
    - kreait/firebase-tokens[1.14.0, ..., 1.15.0] require lcobucci/jwt ^3.4.1|^4.0 -> found lcobucci/jwt[3.4.1, ..., 3.4.x-dev, 4.0.0-alpha1, ..., 4.2.x-dev] but the package is fixed to 3.3.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

I am not sure if the issue is related to the Tymon/JWT pacakge I installed, the tymon/jwt-auth package version is 1.0.2

**Comment by jeromegamez** [comment]
You could try to do a `composer require --with-all-dependencies kreait/laravel-firebase` to see if that helps, but I think your assumption that it has to do with tymon/jwt-auth is correct.

You can read more about it, including a workaround at https://github.com/kreait/firebase-php/discussions/581

(First, require the SDK with the lower version constraint, afterwards require the package)
